import{createClient}from'@supabase/supabase-js';
import{createSharedCookieStorage}from'./sharedAuthStorage.js';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
export const configured=Boolean(url&&key);
export const supabase=configured?createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:createSharedCookieStorage()}}):null;
export const getShowId=()=>{const q=new URLSearchParams(location.search);return q.get('showId')||q.get('show')||''};
export const getLocationId=()=>new URLSearchParams(location.search).get('locationId')||'';
export async function getSession(){if(!supabase)return null;const{data,error}=await supabase.auth.getSession();if(error)throw error;return data.session}
const tokens=new Map(),loadedBibleIds=new Map();
const bibleKey=id=>`bible-location:${id}`;
const budgetKey=id=>`budget-location:${id}`;
const tokenKey=(showId,id)=>`${showId}:${id}`;
const cleanRecord=record=>{const{__remoteUpdatedAt,...rest}=record||{};return rest};
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
async function ensureLocationId(showId,record){const existing=record?.locationId||record?.location?.id;if(existing)return existing;const l=record?.location||{};const{data,error}=await supabase.from('production_locations').insert({show_id:showId,episode_id:record?.episodeName||null,episode_name:record?.episodeName||null,set_name:record?.setName||l.set_name||'',location_name:record?.locationName||l.location_name||'Untitled Location',address:l.address||record?.logistics?.set?.address||'',contact_name:l.contact_name||'',contact_phone:l.contact_phone||'',status:'Bible Draft',source:'bible',metadata:{created_from:'bible'}}).select('id').single();if(error)throw error;record.locationId=data.id;if(record.location)record.location.id=data.id;return data.id}
export async function loadBible(showId){
 if(!supabase)return null;const[{data:legacy,error:legacyError},{data:scoped,error:scopedError}]=await Promise.all([supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key','bible').maybeSingle(),supabase.from('tool_documents').select('tool_key,payload,updated_at').eq('show_id',showId).like('tool_key','bible-location:%')]);if(legacyError)throw legacyError;if(scopedError)throw scopedError;
 const store=legacy?.payload?.bibles?{version:18,activeBibleId:legacy.payload.activeBibleId||null,bibles:{...legacy.payload.bibles}}:{version:18,activeBibleId:null,bibles:{}};if(legacy?.payload&&!legacy.payload.bibles&&(legacy.payload.locationId||legacy.payload.statuses||legacy.payload.values)){const id=legacy.payload.bibleId||`legacy-${legacy.payload.locationId||'default'}`;store.bibles[id]={...legacy.payload,id};store.activeBibleId=id}
 const known=new Map();for(const row of scoped||[]){const locationId=row.tool_key.slice('bible-location:'.length);const record={...(row.payload?.record||row.payload),locationId,__remoteUpdatedAt:row.updated_at};const id=record.id||record.bibleId||`location-${locationId}`;record.id=id;store.bibles[id]=record;tokens.set(tokenKey(showId,locationId),row.updated_at);known.set(locationId,id);if(!store.activeBibleId)store.activeBibleId=id}
 const scopedIds=new Set((scoped||[]).map(r=>r.tool_key.slice('bible-location:'.length)));for(const[id,record]of Object.entries(store.bibles)){const locationId=record.locationId||record.location?.id;if(!locationId||scopedIds.has(locationId))continue;const{data,error}=await supabase.from('tool_documents').upsert({show_id:showId,tool_key:bibleKey(locationId),payload:{version:2,locationId,record:cleanRecord(record),migratedFrom:'bible'}},{onConflict:'show_id,tool_key'}).select('updated_at').single();if(error)throw error;record.__remoteUpdatedAt=data.updated_at;tokens.set(tokenKey(showId,locationId),data.updated_at);known.set(locationId,id)}loadedBibleIds.set(showId,known);return{payload:store,updated_at:[...(scoped||[]).map(r=>r.updated_at),legacy?.updated_at].filter(Boolean).sort().at(-1)}
}
export async function saveBibleDocument(showId,payload){
 if(!supabase)return null;const store=payload?.bibles?payload:{version:18,activeBibleId:payload?.bibleId||null,bibles:{[payload?.bibleId||'legacy']:{...payload,id:payload?.bibleId||'legacy'}}};let latest=null;const conflicts=[];const presentIds=new Set(Object.keys(store.bibles||{}));
 for(const record of Object.values(store.bibles||{})){const locationId=await ensureLocationId(showId,record);const toolKey=bibleKey(locationId);const local=cleanRecord({...record,locationId});const{data:current,error:loadError}=await supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key',toolKey).maybeSingle();if(loadError)throw loadError;const known=tokens.get(tokenKey(showId,locationId))||record.__remoteUpdatedAt||'';const remote=cleanRecord(current?.payload?.record||current?.payload||null);if(current&&same(remote,local)){record.__remoteUpdatedAt=current.updated_at;tokens.set(tokenKey(showId,locationId),current.updated_at);latest=current.updated_at||latest;continue}if(current&&known&&current.updated_at!==known){conflicts.push(locationId);continue}if(current&&!known){conflicts.push(locationId);continue}const{data,error}=await supabase.from('tool_documents').upsert({show_id:showId,tool_key:toolKey,payload:{version:2,locationId,record:local}},{onConflict:'show_id,tool_key'}).select('updated_at').single();if(error)throw error;record.__remoteUpdatedAt=data.updated_at;tokens.set(tokenKey(showId,locationId),data.updated_at);latest=data.updated_at||latest}
 const known=loadedBibleIds.get(showId)||new Map();for(const[locationId,bibleId]of known){if(presentIds.has(bibleId))continue;const{data:current,error:loadError}=await supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key',bibleKey(locationId)).maybeSingle();if(loadError)throw loadError;const expected=tokens.get(tokenKey(showId,locationId));if(!current||!expected||current.updated_at!==expected){conflicts.push(locationId);continue}const{error:tombError}=await supabase.from('tool_documents').upsert({show_id:showId,tool_key:`bible-tombstone:${locationId}`,payload:{version:1,locationId,bibleId,deletedAt:new Date().toISOString()}},{onConflict:'show_id,tool_key'});if(tombError)throw tombError;const{error:deleteError}=await supabase.from('tool_documents').delete().eq('show_id',showId).eq('tool_key',bibleKey(locationId));if(deleteError)throw deleteError;known.delete(locationId);tokens.delete(tokenKey(showId,locationId))}
 if(conflicts.length)console.warn('Skipped stale Bible locations',conflicts);return{updated_at:latest,conflicts}
}
export async function loadBudget(showId){if(!supabase)return null;const[{data:legacy,error:legacyError},{data:scoped,error:scopedError},{data:meta,error:metaError}]=await Promise.all([supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key','budget').maybeSingle(),supabase.from('tool_documents').select('tool_key,payload,updated_at').eq('show_id',showId).like('tool_key','budget-location:%'),supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key','budget-meta').maybeSingle()]);if(legacyError)throw legacyError;if(scopedError)throw scopedError;if(metaError)throw metaError;const byLocation=new Map();for(const b of legacy?.payload?.budgets||[]){if(b.sharedLocationId)byLocation.set(b.sharedLocationId,b)}for(const row of scoped||[]){const id=row.tool_key.slice('budget-location:'.length);byLocation.set(id,{...(row.payload?.budget||row.payload),sharedLocationId:id})}return{payload:{version:2,budgets:[...byLocation.values()],cities:meta?.payload?.cities??legacy?.payload?.cities,vendors:meta?.payload?.vendors??legacy?.payload?.vendors},updated_at:[...(scoped||[]).map(r=>r.updated_at),meta?.updated_at,legacy?.updated_at].filter(Boolean).sort().at(-1)}}
export async function loadLocations(showId){const{data,error}=await supabase.from('production_locations').select('*').eq('show_id',showId).order('updated_at',{ascending:false});if(error)throw error;return(data||[]).filter(r=>!r.metadata?.archived_at)}
export async function updateLocation(locationId,changes){if(!locationId)throw new Error('Missing location ID');const{data:current,error:loadError}=await supabase.from('production_locations').select('metadata').eq('id',locationId).single();if(loadError)throw loadError;const payload={...changes,metadata:{...(current?.metadata||{}),...(changes.metadata||{})},updated_by:(await getSession())?.user?.id||null,updated_at:new Date().toISOString()};const{data,error}=await supabase.from('production_locations').update(payload).eq('id',locationId).select('*').single();if(error)throw error;return data}
export async function archiveLocation(locationId){const{data,error:loadError}=await supabase.from('production_locations').select('metadata,status').eq('id',locationId).single();if(loadError)throw loadError;const{error}=await supabase.from('production_locations').update({status:'Archived',metadata:{...(data.metadata||{}),archived_at:new Date().toISOString(),archived_from_status:data.status||null}}).eq('id',locationId);if(error)throw error}
export async function permanentlyDeleteLocation(showId,locationId,reason='Permanent delete'){const{data:linked,error:linkedError}=await supabase.from('tool_documents').select('tool_key').eq('show_id',showId).in('tool_key',[bibleKey(locationId),budgetKey(locationId)]);if(linkedError)throw linkedError;const{error:tombError}=await supabase.from('tool_documents').upsert({show_id:showId,tool_key:`location-tombstone:${locationId}`,payload:{version:1,locationId,deletedAt:new Date().toISOString(),reason,linkedKeys:(linked||[]).map(x=>x.tool_key)}},{onConflict:'show_id,tool_key'});if(tombError)throw tombError;if(linked?.length){const{error}=await supabase.from('tool_documents').delete().eq('show_id',showId).in('tool_key',linked.map(x=>x.tool_key));if(error)throw error}const{error}=await supabase.from('production_locations').delete().eq('show_id',showId).eq('id',locationId);if(error)throw error}
export function subscribeBible(showId,callback){if(!supabase||!showId)return()=>{};const channel=supabase.channel(`bible:${showId}`).on('postgres_changes',{event:'*',schema:'public',table:'tool_documents',filter:`show_id=eq.${showId}`},p=>{const k=p.new?.tool_key||p.old?.tool_key||'';if(k==='bible'||k.startsWith('bible-location:')||k.startsWith('bible-tombstone:')||k.startsWith('budget-location:'))callback(p)}).on('postgres_changes',{event:'*',schema:'public',table:'production_locations',filter:`show_id=eq.${showId}`},callback).subscribe();return()=>supabase.removeChannel(channel)}
