import{createClient}from'@supabase/supabase-js';
import{createSharedCookieStorage}from'./sharedAuthStorage.js';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
export const configured=Boolean(url&&key);
export const supabase=configured?createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:createSharedCookieStorage()}}):null;
export const getShowId=()=>{const q=new URLSearchParams(location.search);return q.get('showId')||q.get('show')||''};
export const getLocationId=()=>new URLSearchParams(location.search).get('locationId')||'';
export async function getSession(){if(!supabase)return null;const{data,error}=await supabase.auth.getSession();if(error)throw error;return data.session}
const tokens=new Map(),loadedBibleIds=new Map();
const bibleKey=id=>`bible-location:${id}`;
const budgetKey=id=>`budget-location:${id}`;
const bibleTombstoneKey=id=>`bible-tombstone:${id}`;
const locationTombstoneKey=id=>`location-tombstone:${id}`;
const tokenKey=(showId,id)=>`${showId}:${id}`;
const cleanRecord=record=>{const{__remoteUpdatedAt,...rest}=record||{};return rest};
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const latestOf=values=>{const sorted=values.filter(Boolean).sort();return sorted.length?sorted[sorted.length-1]:undefined};
async function lifecycleState(showId,locationId){const[{data:location,error:locationError},{data:locationTomb,error:locationTombError},{data:bibleTomb,error:bibleTombError}]=await Promise.all([supabase.from('production_locations').select('id,metadata,status').eq('show_id',showId).eq('id',locationId).maybeSingle(),supabase.from('tool_documents').select('tool_key').eq('show_id',showId).eq('tool_key',locationTombstoneKey(locationId)).maybeSingle(),supabase.from('tool_documents').select('tool_key').eq('show_id',showId).eq('tool_key',bibleTombstoneKey(locationId)).maybeSingle()]);if(locationError)throw locationError;if(locationTombError)throw locationTombError;if(bibleTombError)throw bibleTombError;return{location,locationDeleted:Boolean(locationTomb),bibleDeleted:Boolean(bibleTomb)}}
async function ensureLocationId(showId,record){const existing=record?.locationId||record?.location?.id;if(existing)return existing;const l=record?.location||{};const{data,error}=await supabase.from('production_locations').insert({show_id:showId,episode_id:record?.episodeName||null,episode_name:record?.episodeName||null,set_name:record?.setName||l.set_name||'',location_name:record?.locationName||l.location_name||'Untitled Location',address:l.address||record?.logistics?.set?.address||'',contact_name:l.contact_name||'',contact_phone:l.contact_phone||'',status:'Bible Draft',source:'bible',metadata:{created_from:'bible'}}).select('id').single();if(error)throw error;record.locationId=data.id;if(record.location)record.location.id=data.id;return data.id}
export async function loadBible(showId){
 if(!supabase)return null;const[{data:legacy,error:legacyError},{data:scoped,error:scopedError},{data:bibleTombs,error:bibleTombError},{data:locationTombs,error:locationTombError}]=await Promise.all([supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key','bible').maybeSingle(),supabase.from('tool_documents').select('tool_key,payload,updated_at').eq('show_id',showId).like('tool_key','bible-location:%'),supabase.from('tool_documents').select('tool_key,payload').eq('show_id',showId).like('tool_key','bible-tombstone:%'),supabase.from('tool_documents').select('tool_key').eq('show_id',showId).like('tool_key','location-tombstone:%')]);if(legacyError)throw legacyError;if(scopedError)throw scopedError;if(bibleTombError)throw bibleTombError;if(locationTombError)throw locationTombError;
 const deletedLocations=new Set((locationTombs||[]).map(x=>x.tool_key.slice('location-tombstone:'.length)));const deletedBibles=new Set((bibleTombs||[]).map(x=>x.tool_key.slice('bible-tombstone:'.length)));const store={version:18,activeBibleId:null,bibles:{}};
 const legacyRecords=legacy?.payload?.bibles?legacy.payload.bibles:(legacy?.payload&&(legacy.payload.locationId||legacy.payload.statuses||legacy.payload.values)?{[legacy.payload.bibleId||`legacy-${legacy.payload.locationId||'default'}`]:{...legacy.payload,id:legacy.payload.bibleId||`legacy-${legacy.payload.locationId||'default'}`}}:{});for(const[id,record]of Object.entries(legacyRecords)){const locationId=record?.locationId||record?.location?.id;if(locationId&&(deletedLocations.has(locationId)||deletedBibles.has(locationId)))continue;store.bibles[id]=record}store.activeBibleId=(legacy?.payload?.activeBibleId&&store.bibles[legacy.payload.activeBibleId])?legacy.payload.activeBibleId:Object.keys(store.bibles)[0]||null;
 const known=new Map();for(const row of scoped||[]){const locationId=row.tool_key.slice('bible-location:'.length);if(deletedLocations.has(locationId)||deletedBibles.has(locationId))continue;const record={...(row.payload?.record||row.payload),locationId,__remoteUpdatedAt:row.updated_at};const id=record.id||record.bibleId||`location-${locationId}`;record.id=id;store.bibles[id]=record;tokens.set(tokenKey(showId,locationId),row.updated_at);known.set(locationId,id);if(!store.activeBibleId)store.activeBibleId=id}
 const scopedIds=new Set((scoped||[]).map(r=>r.tool_key.slice('bible-location:'.length)));for(const[id,record]of Object.entries(store.bibles)){const locationId=record.locationId||record.location?.id;if(!locationId||scopedIds.has(locationId)||deletedLocations.has(locationId)||deletedBibles.has(locationId))continue;const state=await lifecycleState(showId,locationId);if(state.locationDeleted||state.bibleDeleted||!state.location)continue;const{data,error}=await supabase.from('tool_documents').upsert({show_id:showId,tool_key:bibleKey(locationId),payload:{version:2,locationId,record:cleanRecord(record),migratedFrom:'bible'}},{onConflict:'show_id,tool_key'}).select('updated_at').single();if(error)throw error;record.__remoteUpdatedAt=data.updated_at;tokens.set(tokenKey(showId,locationId),data.updated_at);known.set(locationId,id)}loadedBibleIds.set(showId,known);return{payload:store,updated_at:latestOf([...(scoped||[]).map(r=>r.updated_at),legacy?.updated_at])}
}
export async function saveBibleDocument(showId,payload){
 if(!supabase)return null;const store=payload?.bibles?payload:{version:18,activeBibleId:payload?.bibleId||null,bibles:{[payload?.bibleId||'legacy']:{...payload,id:payload?.bibleId||'legacy'}}};let latest=null;const conflicts=[];const presentIds=new Set(Object.keys(store.bibles||{}));
 for(const record of Object.values(store.bibles||{})){const locationId=await ensureLocationId(showId,record);const state=await lifecycleState(showId,locationId);if(state.locationDeleted||state.bibleDeleted||!state.location||state.location.metadata?.archived_at){conflicts.push(locationId);continue}const toolKey=bibleKey(locationId);const local=cleanRecord({...record,locationId});const{data:current,error:loadError}=await supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key',toolKey).maybeSingle();if(loadError)throw loadError;const known=tokens.get(tokenKey(showId,locationId))||record.__remoteUpdatedAt||'';const remote=cleanRecord(current?.payload?.record||current?.payload||null);if(current&&same(remote,local)){record.__remoteUpdatedAt=current.updated_at;tokens.set(tokenKey(showId,locationId),current.updated_at);latest=current.updated_at||latest;continue}if(current&&known&&current.updated_at!==known){conflicts.push(locationId);continue}if(current&&!known){conflicts.push(locationId);continue}const{data,error}=await supabase.from('tool_documents').upsert({show_id:showId,tool_key:toolKey,payload:{version:2,locationId,record:local}},{onConflict:'show_id,tool_key'}).select('updated_at').single();if(error)throw error;record.__remoteUpdatedAt=data.updated_at;tokens.set(tokenKey(showId,locationId),data.updated_at);latest=data.updated_at||latest}
 const known=loadedBibleIds.get(showId)||new Map();for(const[locationId,bibleId]of [...known]){if(presentIds.has(bibleId))continue;const{data:current,error:loadError}=await supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key',bibleKey(locationId)).maybeSingle();if(loadError)throw loadError;const expected=tokens.get(tokenKey(showId,locationId));if(!current||!expected||current.updated_at!==expected){conflicts.push(locationId);continue}const{error:tombError}=await supabase.from('tool_documents').upsert({show_id:showId,tool_key:bibleTombstoneKey(locationId),payload:{version:2,locationId,bibleId,deletedAt:new Date().toISOString(),recordSnapshot:current.payload,updatedAt:current.updated_at}},{onConflict:'show_id,tool_key'});if(tombError)throw tombError;const{error:deleteError}=await supabase.from('tool_documents').delete().eq('show_id',showId).eq('tool_key',bibleKey(locationId));if(deleteError)throw deleteError;known.delete(locationId);tokens.delete(tokenKey(showId,locationId))}
 if(conflicts.length)console.warn('Skipped stale or lifecycle-blocked Bible locations',conflicts);return{updated_at:latest,conflicts}
}
export async function loadCalendarDocument(showId){if(!supabase||!showId)return null;const{data,error}=await supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key','calendar').maybeSingle();if(error)throw error;return data}
export async function loadBudget(showId){if(!supabase)return null;const[{data:legacy,error:legacyError},{data:scoped,error:scopedError},{data:meta,error:metaError},{data:tombs,error:tombError}]=await Promise.all([supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key','budget').maybeSingle(),supabase.from('tool_documents').select('tool_key,payload,updated_at').eq('show_id',showId).like('tool_key','budget-location:%'),supabase.from('tool_documents').select('payload,updated_at').eq('show_id',showId).eq('tool_key','budget-meta').maybeSingle(),supabase.from('tool_documents').select('tool_key').eq('show_id',showId).like('tool_key','location-tombstone:%')]);if(legacyError)throw legacyError;if(scopedError)throw scopedError;if(metaError)throw metaError;if(tombError)throw tombError;const deleted=new Set((tombs||[]).map(x=>x.tool_key.slice('location-tombstone:'.length)));const byLocation=new Map();for(const b of legacy?.payload?.budgets||[]){if(b.sharedLocationId&&!deleted.has(b.sharedLocationId))byLocation.set(b.sharedLocationId,b)}for(const row of scoped||[]){const id=row.tool_key.slice('budget-location:'.length);if(!deleted.has(id))byLocation.set(id,{...(row.payload?.budget||row.payload),sharedLocationId:id})}return{payload:{version:2,budgets:[...byLocation.values()],cities:meta?.payload?.cities??legacy?.payload?.cities,vendors:meta?.payload?.vendors??legacy?.payload?.vendors},updated_at:latestOf([...(scoped||[]).map(r=>r.updated_at),meta?.updated_at,legacy?.updated_at])}}
export async function saveBudgetVendorLibrary(showId,vendors){if(!supabase||!showId)throw new Error('Supabase unavailable');const[{data:meta,error:metaError},{data:legacy,error:legacyError}]=await Promise.all([supabase.from('tool_documents').select('payload').eq('show_id',showId).eq('tool_key','budget-meta').maybeSingle(),supabase.from('tool_documents').select('payload').eq('show_id',showId).eq('tool_key','budget').maybeSingle()]);if(metaError)throw metaError;if(legacyError)throw legacyError;const metaPayload={...(meta?.payload||{}),version:2,vendors};const{error}=await supabase.from('tool_documents').upsert({show_id:showId,tool_key:'budget-meta',payload:metaPayload},{onConflict:'show_id,tool_key'});if(error)throw error;if(legacy){const{error:legacySaveError}=await supabase.from('tool_documents').update({payload:{...legacy.payload,vendors}}).eq('show_id',showId).eq('tool_key','budget');if(legacySaveError)throw legacySaveError}return metaPayload}
export async function loadLocations(showId){const{data,error}=await supabase.from('production_locations').select('*').eq('show_id',showId).order('updated_at',{ascending:false});if(error)throw error;return(data||[]).filter(r=>!r.metadata?.archived_at)}
export async function updateLocation(locationId,changes){if(!locationId)throw new Error('Missing location ID');const{data:current,error:loadError}=await supabase.from('production_locations').select('metadata').eq('id',locationId).single();if(loadError)throw loadError;if(current?.metadata?.archived_at)throw new Error('Archived locations cannot be edited');const payload={...changes,metadata:{...(current?.metadata||{}),...(changes.metadata||{})},updated_by:(await getSession())?.user?.id||null,updated_at:new Date().toISOString()};const{data,error}=await supabase.from('production_locations').update(payload).eq('id',locationId).select('*').single();if(error)throw error;return data}
export async function archiveLocation(locationId){const{data,error:loadError}=await supabase.from('production_locations').select('metadata,status').eq('id',locationId).single();if(loadError)throw loadError;const{error}=await supabase.from('production_locations').update({status:'Archived',metadata:{...(data.metadata||{}),archived_at:new Date().toISOString(),archived_from_status:data.status||null}}).eq('id',locationId);if(error)throw error}
export async function permanentlyDeleteLocation(showId,locationId,reason='Permanent delete'){const[{data:linked,error:linkedError},{data:locationRecord,error:locationError}]=await Promise.all([supabase.from('tool_documents').select('tool_key,payload,updated_at').eq('show_id',showId).in('tool_key',[bibleKey(locationId),budgetKey(locationId)]),supabase.from('production_locations').select('*').eq('show_id',showId).eq('id',locationId).maybeSingle()]);if(linkedError)throw linkedError;if(locationError)throw locationError;const{error:tombError}=await supabase.from('tool_documents').upsert({show_id:showId,tool_key:locationTombstoneKey(locationId),payload:{version:2,locationId,deletedAt:new Date().toISOString(),reason,locationSnapshot:locationRecord||null,linkedRecords:(linked||[]).map(x=>({toolKey:x.tool_key,payload:x.payload,updatedAt:x.updated_at}))}},{onConflict:'show_id,tool_key'});if(tombError)throw tombError;if(linked?.length){const{error}=await supabase.from('tool_documents').delete().eq('show_id',showId).in('tool_key',linked.map(x=>x.tool_key));if(error)throw error}const{error}=await supabase.from('production_locations').delete().eq('show_id',showId).eq('id',locationId);if(error)throw error}
export function subscribeBible(showId,callback){if(!supabase||!showId)return()=>{};const channel=supabase.channel(`bible:${showId}`).on('postgres_changes',{event:'*',schema:'public',table:'tool_documents',filter:`show_id=eq.${showId}`},p=>{const k=p.new?.tool_key||p.old?.tool_key||'';if(k==='bible'||k==='calendar'||k==='budget-meta'||k.startsWith('bible-location:')||k.startsWith('bible-tombstone:')||k.startsWith('location-tombstone:')||k.startsWith('budget-location:'))callback(p)}).on('postgres_changes',{event:'*',schema:'public',table:'production_locations',filter:`show_id=eq.${showId}`},callback).subscribe();return()=>supabase.removeChannel(channel)}
